import * as babel from '@babel/core';
import { bluntInstrumentPlugin } from '.';
import { examples } from 'blunt-instrument-test-resources';
import { getNodeId, attachCodeSlicesToAST, ASTQuerier } from 'blunt-instrument-ast-utils';
import cloneDeep from 'lodash/cloneDeep';

/**
 * Runs blunt-instrument-babel-plugin on the given code and returns the instrumented code.
 * @param {string} code
 * @param {object} pluginOpts - options for the blunt-instrument babel plugin
 * @param {object} babelOpts - options for babel
 * @returns {string}
 */
function transform(code, pluginOpts = {}, babelOpts = {}) {
  return babel.transformSync(code, { plugins: [[bluntInstrumentPlugin, pluginOpts]] , ...babelOpts });
}

/**
 * Runs eval on the given code within global context.
 * @param {string} code - code to eval
 * @returns {*} - result of eval
 */
function codeEval(code) {
  return (0, eval(code));
}

/**
 * Runs blunt-instrument-babel-plugin on the given code, then runs the instrumented code.
 * An object named "output" will be in scope for the code; the code can set properties on
 * it to communicate with the caller. The return value of this method is the "output" object,
 * which also contains an "instrumentation" property which is the instrumentation object
 * generated by blunt-instrument-babel-plugin, a "code" property which is the input code,
 * and an "instrumented" property which is the instrumented code.
 * 
 * @param {string} code
 * @returns {object}
 */
function biEval(code, pluginOpts = {}) {
  const { code: instrumented } = transform(code, { outputs: { assignTo: 'output.instrumentation' }, ...pluginOpts});
  const wrapped = `
    (function() {
      let output = {};
      (function() {${instrumented}})()
      return output;
    })()
  `;
  
  const result = codeEval(wrapped);
  
  const astClone = cloneDeep(result.instrumentation.ast);
  attachCodeSlicesToAST(astClone, code);
  const astq = new ASTQuerier(astClone);
  
  return { astq, code, instrumented, ...result };
}

function trevsForNode({ instrumentation: { trace } }, node) {
  return trace.filter((trev) => trev.nodeId === getNodeId(node));
}

function exprValues(output, target) {
  const nodes = output.astq.getNodesByCodeSlice(target);
  const trevs = nodes.flatMap(node => trevsForNode(output, node));
  const exprTrevs = trevs.filter((trev) => trev.type === 'expr');
  return exprTrevs.map(trev => trev.data);
}

function exprValue(output, target) {
  const vals = exprValues(output, target);
  expect(vals).toHaveLength(1);
  return vals[0];
}

describe('instrumentation object output', () => {
  describe('assignTo', () => {
    it('assigns to a specified variable', () => {
      const { code } = transform('const x = 1', { outputs: { assignTo: 'result' }});
      const wrapped = `
        (function() {
          let result;
          (function() {${code}})()
          return result;
        })()
      `;
      const result = codeEval(wrapped);
      expect(result).toHaveProperty('ast');
      expect(result).toHaveProperty('trace');
    });

    it('assigns to an object member', () => {
      const { code } = transform('const x = 1', { outputs: { assignTo: 'this.result' }});
      const wrapped = `
        (function() {
          let obj = {};
          obj.fn = function(){${code}};
          obj.fn();
          return obj.result;
        })()
      `;
      const result = codeEval(wrapped);
      expect(result).toHaveProperty('ast');
      expect(result).toHaveProperty('trace');
    });
  });

  describe('exportAs', () => {
    it('exports the specified name', () => {
      const { code } = transform('const x = 1', { outputs: { exportAs: 'result' }});
      const wrapped = `
        (function() {
          let exports = {};
          (function(){${code}})();
          return exports;
        })()
      `;
      const exported = codeEval(wrapped);
      expect(exported.__esModule).toBe(true);
      expect(exported.result).toHaveProperty('ast');
      expect(exported.result).toHaveProperty('trace');
    });
  });
});

describe('general examples', () => {
  test('factorial', () => {
    const output = biEval(`
      function fac(n) {
        return n == 1 ? 1 : n * fac(n - 1);
      }

      output.fac5 = fac(5);
    `);
    expect(output.fac5).toEqual(120);
    expect(exprValues(output, 'fac(n - 1)')).toEqual([1, 2, 6, 24]);
    expect(exprValues(output, 'n == 1')).toEqual([false, false, false, false, true]);
  });
});

describe('special case syntax handling', () => {
  describe('method invocations', () => {
    test('this is bound correctly when invoking a method', () => {
      const output = biEval(`
        const obj = { val: 'old' };
        const fn = function() { this.val = 'new'; };
        obj.fn = fn;
        obj.fn();
        output.val = obj.val;
      `);
      expect(output.val).toEqual('new');
      expect(exprValue(output, 'this')).toEqual({ val: 'old'}); // note, this would also include an fn property if the serializer were better
      expect(exprValues(output, 'obj.fn')).toHaveLength(0);
    });

    test('this is bound correctly when invoking the result of a getter, and the getter is only called once', () => {
      // This test exists as a reminder that translating
      // `x.y` to `trace(x.y); x.y()` would not be acceptable.
      // FIXME: currently this uses the `none` transcriber because the only
      // other transcriber I've written invokes JSON.stringify, which in turn
      // calls all the getters on objects. The instrumenter adds tracing for the
      // value of `this` to all getters, leading to infinite recursion.
      const output = biEval(`
        const obj = {
          count: 0,
          get fn() {
            return function() {
              const val = this.count + 1;
              this.count = val;
            }
          },
        };
        obj.fn();
        output.count = obj.count;
      `, { valueTranscriber: 'none' });
      expect(output.count).toEqual(1);
      expect(exprValue(output, 'this.count')).toEqual(0);
      expect(exprValues(output, 'obj.fn')).toHaveLength(0);
    });
  });

  test('`arguments` is bound correctly', () => {
    const output = biEval(`
      function foo() {
        return arguments.length * (arguments[0] + arguments[1]);
      }
      output.result = foo(4, 5, 10, 12);
    `);
    expect(output.result).toEqual(36);
  });

  test('assign to MemberExpression', () => {
    const output = biEval('const a = [null]; a[0] = 1; output.a0 = a[0];');
    expect(output.a0).toEqual(1);
    expect(exprValue(output, 'a[0] = 1')).toEqual(1);
  });

  describe('UpdateExpression handling', () => {
    test('postfix ++ operator', () => {
      const output = biEval('let x = 1; const a = x++; output.a = a; output.x = x;');
      expect(output.a).toEqual(1);
      expect(output.x).toEqual(2);
      expect(exprValue(output, 'x++')).toEqual(1);
    });
    
    test('prefix ++ operator', () => {
      const output = biEval('let x = 1; const a = ++x; output.a = a; output.x = x;');
      expect(output.a).toEqual(2);
      expect(output.x).toEqual(2);
      expect(exprValue(output, '++x')).toEqual(2);
    });

    test('postifx operator rewrite binds `arguments` correctly', () => {
      const output = biEval(`
        function foo() {
          output.original = arguments[0]++;
          return arguments[0];
        }
        output.result = foo(3);
      `);
      expect(output.result).toEqual(4);
      expect(output.original).toEqual(3);
    });

    test('postfix -- operator', () => {
      const output = biEval('let x = 2; const a = x--; output.a = a; output.x = x;');
      expect(output.a).toEqual(2);
      expect(output.x).toEqual(1);
      expect(exprValue(output, 'x--')).toEqual(2);
    });

    test('prefix -- operator', () => {
      const output = biEval('let x = 2; const a = --x; output.a = a; output.x = x;');
      expect(output.a).toEqual(1);
      expect(output.x).toEqual(1);
      expect(exprValue(output, '--x')).toEqual(1);
    });
    
    test('+= operator', () => {
      const output = biEval('let x = 1; const a = x += 1; output.a = a; output.x = x;');
      expect(output.a).toEqual(2);
      expect(output.x).toEqual(2);
      expect(exprValue(output, 'x += 1')).toEqual(2);
    });
  });
});

describe('demo examples', () => {
  for (const key in examples) {
    test(key, () => {
      const output = biEval(examples[key]);
      expect(output.instrumented).toMatchSnapshot();
      expect(output.instrumentation.trace).toMatchSnapshot();
    });
  }
});
